version: '3.5'

services:
  php-apache-dev:
    image: php-apache-dev
    container_name: php-apache-dev
    build:
      context: '.'
      args:
        uid: 1444
    environment:
      - APACHE_RUN_USER=#1444
      - APACHE_RUN_GROUP=#1444
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    networks:
        php-network-dev:
            aliases:
                - php-apache-dev

networks:
  php-network-dev:
    name: php-network-dev
    external: 
      name: db-network