version: '3.5'

services:
  web-dev:
    image: web-dev
    container_name: web-dev
    build:
      context: '.'
      args:
        uid: 1444
    environment:
      - APACHE_RUN_USER=#1444
      - APACHE_RUN_GROUP=#1444
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    networks:
        web-network-dev:
            aliases:
                - web-dev

networks:
  web-network-dev:
    name: web-network-dev
    external: 
      name: db-network
