# Use postgres/example user/password credentials
version: '3.5'

services:

  postgresql:
    image: postgres
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    networks: 
            genesis:
                aliases: 
                    - postgres

  adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    environment:
        ADMINER_DESIGN: flat
    ports:
      - 5433:8080
    networks: 
            genesis:
                aliases: 
                    - adminer
                    
networks:
    genesis:
        external:
            name: genesis