version: '3.5'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    container_name: app-mariadb
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    networks: 
            db:
                aliases: 
                    - mariadb
                    
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app-phpmyadmin
        links: 
            - mariadb
        environment: 
            PMA_HOST: mariadb
            PMA_PORT: 3306
        ports: 
            - 3316:80
        networks:
            db:
                aliases: 
                    - phpmyadmin

volumes:
  mariadb_data:
    driver: local

networks: 
    db:
        name: db-network
